### ISSUE TITLE
Classes code

### ISSUE THREAD

**Issue by TorchedSammy** [hibiscus-eris/hibiscus#1]
My only gripe about your code is the fact that functions are in the constructor itself and I really want to know just why
```js
class head {
    constructor() {
        this.shake = () => {
            console.log('smh')
        }
    }
}
```
actually triggered >:|

**Comment by DonovanDMC** [comment]
Jesus why did you bring it up

**Comment by DonovanDMC** [comment]
I hate this so much

**Comment by Skullbite** [comment]
either post a solution or shut up, you have 2 days boomer

**Comment by Skullbite** [comment]
it's been 2 days boomer

**Comment by TorchedSammy** [comment]
```js
class head {
    constructor() {    }

    shake() {
        console.log('yes smh')
    }
}````

**Comment by DonovanDMC** [comment]
PascalCase clases smh
